In [1]:
import torch  
import numpy as np 
a= [1,2,3] 
t = torch.Tensor(a)  # 数组转tensor
t 

tensor([1., 2., 3.])

In [7]:
t1 = torch.Tensor(np.array([2,3]))
t1

tensor([2., 3.])

In [12]:
t1 = torch.tensor([1,1,1])  # 数组转tensor
t2 = torch.Tensor(2,3)  # 随机2*3矩阵
t3 = torch.ones(2,1)  # 填充1
t4 = torch.zeros(1,2)  # 填充0
t5 = torch.eye(2,2)  # 返回二维张量，对角线上是1，其它地方是0  

t5.size()         # tensor的size() 
torch.numel(t5)  # tensor中元素进行计数  

4

### 其他常见  tensor操作  
1. 统计tensor中总共有多少元素 torch.numel(t)

###  初始化操作    
1. torch自己进行初始化  
2. 通过 numpy、list进行转换  
3. 借助已有tensor进行转换 

#### 不懂
* torch.tensor 总是会复制 data, 如果你想避免复制，可以使 torch.Tensor. detach()，如果是从 numpy 中获得数据，那么你可以用 torch.from_numpy(), 注from_numpy() 是共享内存的
* array([2,3]) 和 [2,3]的区别

In [6]:
# torch自己进行初始化  
t1 = torch.Tensor(2,3)  
t2 = torch.tensor([1,1,1])

t3 = torch.ones(2,1)
t4 = torch.zeros(1,3) 
t5 = torch.eye(2,2)  

t6 = torch.rand(2,2)     # 均匀分布 
t7 = torch.randn(t6.size())    # 标准正态分布   
# # print(type(t7.size()))    # class  torch.Size


# 借助已有 tensor,主要是size
t8 = torch.empty(2,3)  # 空 tensor ，里面是无穷接近于0的数字
t9 = torch.empty_like(t8)  # 张量返回一个与输入大小相同的未初始化的张量
t10 = torch.full((1,2),2)  # 返回大小为sizes,单位值为fill_value的矩阵
t11 = torch.full_like(t9,1)  # 返回与input相同size，单位值为fill_value的矩阵  
print(t10)

# 通过numpy 和 list    
# Tensor 和  np.array() 之间共享内存，也就意味着: 其中一个发生变化，另外一个也会发生变化  
list1 = [1,2,3,4]
np1 = np.array([2,3])
# print(np1)
t12 = torch.Tensor(list1)  
t13 = torch.Tensor(np.array([1,2,3,4,5,6]))
t14 = torch.from_numpy(np1)  
# print(t14)
np1 = np.array([1,2,3,4,5,6,8])
np2 = t14.numpy()     # tensor转换为 numpy     |   list好像是不可以直接进行转换  
# np2


tensor([[2., 2.]])


###  计算操作 - 基本数学运算    
 1. 加法
2. 减法  
 3. 元素乘积  
 4. 除法  
5.乘法
 5.1 二维矩阵乘法 
   5.2 多维矩阵相乘 
 6. 幂运算  
 7. 开方运算 
 8. 指数和对数运算  
 9. 近似值运算 

#### 问题
* torch.mm & torch.matmul &torch.mul 的区别
https://blog.csdn.net/da_kao_la/article/details/87484403
* 广播就是增加维度再删除？




In [3]:
###  计算操作 - 基本数学运算    
# 1. 加法
# 2. 减法  
# 3. 元素乘积  
# 4. 除法  
# 5.乘法
#   5.1 二维矩阵乘法 
#   5.2 多维矩阵相乘 
# 6. 幂运算  
# 7. 开方运算 
# 8. 指数和对数运算  
# 9. 近似值运算 
# 10. 裁剪运算： 对于tensor中的元素进行范围过滤，常用于梯度 裁剪  

a1 = torch.rand(3,4) 
a2 = torch.rand(4)  
a3 = a1+a2 
a4 = torch.add(a1,a2)   # 加法

a5 = a1-a2
a6 = torch.sub(a1,a2)   # 减法 

a7 = a1*a2
a8 = torch.mul(a1,a2)  # 3.元素乘法 

a9 = a1/a2
a10 = torch.div(a1,a2)  # 4.元素除法


b1 = torch.ones(2,1) 
b2 = torch.ones(1,2)

b3 = torch.mm(b1,b2)
b4 = torch.matmul(b1,b2)
b5 = b1@b2                 # 5.1 三种 二维矩阵相乘 

# 多维矩阵乘法： dim>2的tensor,定义其矩阵乘法仅在最后两个维度上面进行，要求前面的维度必须保持一致，
# 就像矩阵索引一样，并且 运算只有  torch.matmul()  
# 前面的‘矩阵索引维度’如果符合 Broadcasting机制，也会自动做广播，然后相乘  
c1 = torch.ones(2,2,2,1)  
c2 = torch.rand(1,2,1,2)
c3 = torch.matmul(c1,c2)               # 多维tensor的矩阵乘法
c1,c2,c3,c3.size()  


c4 = torch.full([2,2],3)
c5 = c4 ** 2 
c6 = c4.pow(3)                       # 6.幂运算 
print(c4,c5,c6)

c7 = c5 ** (0.5)
c8 = c5.sqrt()                       # 7. tensor的开方运算
c9 = c5.rsqrt()
c7,c8,c9

# 指数与对数运算  
# 注意： log是以 自然对数为底数的， 以2为底用 log2, 以10为底用log10  

d1 = torch.ones(2,2)  
d2 = torch.exp(d1)
d3 = torch.log(d2)

d4 = torch.full([2,2],10)
d5 = torch.log10(d4)                 # 9. 取对数运算

d1,d2,d3,d5   


d6 = torch.tensor(3.14) 
d7 = d6.floor()   # 取下 3.
d8 = d6.ceil()    # 取上  4.
d9 = d6.trunc()   # 取整数  3.                # 其他取值运算
d10 = d6.frac()    # 取小数  0.1400
d11 = d6.round()    # 四舍五入  3.


# 裁剪运算： 对 tensor中的元素进行范围过滤，不符合条件的可以把它变换到 范围内部(边界)上，
# 常用于梯度剪裁(Gradient Clipping)，即在发生梯度离散  或者  梯度爆炸 时对于梯度的处理，实际应用 
# 可以查看梯度的(L2范数)模来看看需不需要处理： W.grad.norm(2)  
grad = torch.rand(2,3) * 15 
g1 = grad.max()
g2 = grad.min()  
g3 = grad.median()  

g4 = grad.clamp(10) 
g5 = grad.clamp(3,10)   # 10. 梯度裁剪

grad,g1,g2,g3,g4,g5

tensor([[3., 3.],
        [3., 3.]]) tensor([[9., 9.],
        [9., 9.]]) tensor([[27., 27.],
        [27., 27.]])
tensor(3.1400) tensor(3.) tensor(4.) tensor(3.) tensor(0.1400) tensor(3.)
1


(tensor([[ 6.0464,  3.5679, 12.3470],
         [ 1.0466, 10.0537,  7.9185]]),
 tensor(12.3470),
 tensor(1.0466),
 tensor(6.0464),
 tensor([[10.0000, 10.0000, 12.3470],
         [10.0000, 10.0537, 10.0000]]),
 tensor([[ 6.0464,  3.5679, 10.0000],
         [ 3.0000, 10.0000,  7.9185]]))

### pytorch 的 tensor 的统计属性  
1. 范数  
2. 常用操作: 
2.1 均值、累加、最小、最大、累积  
2.2 直接使用max | min 配合 dim参数也可以获得最值索引，同时得到最值的具体值  
2.3 使用 keepdim=True可以保持应有的dim,即仅仅是 将求最值的那个 dim的size变成了1，返回的   
结果是符合原 tensor语义的。  
2.4 取 前K大/ 前K小/ 第K小 的概率值及其索引  
2.5 比较操作  




In [130]:
e1 = torch.full([8],1)
e2 = e1.reshape([2,4])
e3 = e1.reshape([2,2,2]) 

e4 = e1.norm(1) 
e5 = e2.norm(1)   # L1范数: 所有元素绝对值求和  

e6 = e1.norm(2) 
e7 = e2.norm(2)   # L2范数: 平方和开根号  

e8 = e1.norm(1,dim=0) 
e9 = e2.norm(2,dim=1)   # 根据指定维度 求范数  


f1 = torch.arange(8).reshape(2,4).float()  
f2 = f1.mean()    # 均值
f3 = f1.sum()     # 累加
f4 = f1.min()     # 最小 
f5 = f1.max()     # 最大
f6 = f1.prod()    # 累积

f7 = f1.argmax()
f8 = f1.argmin()   # 整个tensor打平之后的 最大、最小值 索引 
# 上述的  argmax() 、 argmin() 操作会默认将 tensor打平后取最大值索引、  
#  最小值索引，如果不希望tensor打平，而是求 给定维度上的索引，需要指定在哪一个
# 维度上面求 最大值索引 和 最小值索引。  

f9 = torch.rand(2,2,2)
f10 = f9.argmax(dim =0)
f10_ = f9.max(dim=0)
f10_1 = f9.max(dim=0,keepdim=True)   # 三种方法后面好好再看看
# f11 = f9.argmax(dim=1)
# f12 = f9.argmax(dim=2)

# topk概率选择 
# 使用 topk代替max可以完成更加灵活的需求， largest=False, kthvalue
# 还可以取第k小的概率值及其索引  
# 不给定dim则默认最后一维，largest=False代表取小

h1 = torch.randn(2,10)  
h2 = h1.topk(3,dim=1)
h3 = h1.topk(3,dim=1,largest=False)  # 概率最小 【前】 3 
h4 = h1.kthvalue(8,dim=1)    # 求 【第】 8概率小的 
h1,h2,h3,h4   



# 比较操作  
k1 = torch.randn(2,3)
k2 = torch.randn(2,3)  
k3 = k1>0   
k4 = torch.gt(k1,0)   # 两种方法判断 K1是否大于0，是 对应位置返回1，否 0

k5 = a != 0              # 比较每个位置是否 等于  0

k6 = torch.equal(k1,k2)
k3,k4,k5
k6

False

### 维度变换操作    
1. 拼接  torch.cat(seq,dim,out) 
2. 维度扩展  
3. 压缩  
4. 转置   
5. 重复   


#### 链接  
1. https://blog.csdn.net/TH_NUM/article/details/83088915   
2. https://blog.csdn.net/weixin_44613063/article/details/89521464 

In [15]:
# 向量拼接  
# 1.torch.cat()  
# 2. torch.stack()

# torch.cat(seq,dim=0,out=None)
# 除去seq中tensor的该维度，然后按照指定的维度进行拼接，但是总的维度数目不变，拼接的内容可能是 tesnor可能是里面的最后一个维度的数字
import torch
h_1 = torch.randn(2,3)
h_2 = torch.cat((h_1,h_1,h_1),0) 
print(h_2)  # [2,9]  [6,3]

tensor([[ 0.5189, -1.8552,  0.1157],
        [ 1.0232,  0.9460, -0.9362],
        [ 0.5189, -1.8552,  0.1157],
        [ 1.0232,  0.9460, -0.9362],
        [ 0.5189, -1.8552,  0.1157],
        [ 1.0232,  0.9460, -0.9362]])


In [14]:
# torch.stack((Tensor),dim)    

# 多出一个维度，按照指定维度把 tensor中对应的内容，叠加起来增加一个维度
h_3 = torch.IntTensor([[1,2,3],[11,22,33]])
h_4 = torch.IntTensor([[4,5,6],[44,55,66]])

h_5 =torch.stack([h_3,h_4],0)
h_6 =torch.stack([h_3,h_4],1)
h_7 =torch.stack([h_3,h_4],2)
print(h_5.size(),h_5)   # [2,2,3]
print(h_6.size(),h_6)
print(h_7.size(),h_7)
# h_5, dim = 0时， c = [ a, b]
# h_6, dim =1 时， d = [ [a[0] , b[0] ] , [a[1], b[1] ] ]
# h_7, dim = 2 时， e=[[[a[0][0],b[0][0]],[a[0][1],b[0][1]],[a[0][2],b[0][2]]],[[a[1][0],b[1][0]],[a[1][1],b[0][1]],[a[1][2],b[1][2]]]]e = [ [ [ a[0][0], b[0][0] ] , [ a[0][1], b[0][1] ] , [ a[0][2],b[0][2] ] ] , [ [ a[1][0], b[1][0] ] , [ a[1][1], b[0][1] ] , [ a[1][2],b[1][2] ] ] ]e=[[[a[0][0],b[0][0]],[a[0][1],b[0][1]],[a[0][2],b[0][2]]],[[a[1][0],b[1][0]],[a[1][1],b[0][1]],[a[1][2],b[1][2]]]]

torch.Size([2, 2, 3]) tensor([[[ 1,  2,  3],
         [11, 22, 33]],

        [[ 4,  5,  6],
         [44, 55, 66]]], dtype=torch.int32)
torch.Size([2, 2, 3]) tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[11, 22, 33],
         [44, 55, 66]]], dtype=torch.int32)
torch.Size([2, 3, 2]) tensor([[[ 1,  4],
         [ 2,  5],
         [ 3,  6]],

        [[11, 44],
         [22, 55],
         [33, 66]]], dtype=torch.int32)


In [9]:
# 扩大向量  
# 1. torch.Tensor.expand(*sizes) --> Tensor   
# 返回张量的一个新视图，可以将张量的单个维度扩大为 更大的尺寸  
# 张量也可以扩大为 更高维，新增加的维度将 附在前面。  
# 扩大张量不需要分配新内存，仅仅是新建一个张量的视图。 任意一个一维张量在不分配新内存情况下都可以扩展为任意的维度。  
# 传入 -1 意味着 维度扩大不涉及这个维度  
# 参数: * sizes(torch.Size or int )  - 想要扩展的目标维度  
h_8 = torch.Tensor([[1],[2],[3]])  
print('h_8的size:',h_8.size())
h_9 = h_8.expand(2,3,5)   # 注意不管怎么扩展 原始tensor的第0维度数值不能变化，要不然 tensor不知道扩展什么。 也就是广播  即3不能变
h_10 = h_8.expand(2,3,1)
print(h_9,h_9.size())

h_8的size: torch.Size([3, 1])
tensor([[[1., 1., 1., 1., 1.],
         [2., 2., 2., 2., 2.],
         [3., 3., 3., 3., 3.]],

        [[1., 1., 1., 1., 1.],
         [2., 2., 2., 2., 2.],
         [3., 3., 3., 3., 3.]]]) torch.Size([2, 3, 5])


In [31]:
# 压缩张量  
# torch.squeeze(input,dim=None) --> Tensor   
# 除去输入张量input中数值为1的维度，并返回新的张量。  
# 如果输入张量的维度形状为(A*1*B*C*1*D),那么输出张量的形状为(A*B*C*D)  
# 当通过dim参数进行指定维度时，维度压缩操作只会在指定的维度上进行。 如果输入张量形状为（A*1*B）,squeeze(input,0)会保持张量的维度
# 不变，只有在执行squeeze(input,1)时，输入张量的形状会被压缩至(A*B)  
# 如果一个张量只有一个维度，那么它不会受到上述方法的影响  
# 输出的张量与原张量共享内存，如果改变其中的一个，另一个也会改变  
# 参数: 
#  * input(Tensor) - 输入张量 
#  * dim(int,optional) - 如果给定，则只会在给定维度压缩  
#  * out(Tensor,optional) -输出张量  

k_1 = torch.zeros(2,1,2,1,2)  
print('k_1.size() : ',k_1.size()) 
k_2 = torch.squeeze(k_1) 
print('k_2: ',k_2.size(),k_2)  
k_3 = torch.squeeze(k_1,0)
print('k_3:',k_3.size(),k_3)  
k_4 = torch.squeeze(k_1,1)
print('k_4: ',k_4.size(),k_4)   


# torch.unsqueeze(input,dim)  
# 返回一个新的张量，对于 输入的指定位置插入维度1  
# 返回张量与输入张量共享内存。 
# 如果 dim 为负数，则将会被转为 dim+input.dim()+1  
k_4_1 = k_1.unsqueeze(0) 
print('k_4_1: ',)

k_1.size() :  torch.Size([2, 1, 2, 1, 2])
k_2:  torch.Size([2, 2, 2]) tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])
k_3: torch.Size([2, 1, 2, 1, 2]) tensor([[[[[0., 0.]],

          [[0., 0.]]]],



        [[[[0., 0.]],

          [[0., 0.]]]]])
k_4:  torch.Size([2, 2, 1, 2]) tensor([[[[0., 0.]],

         [[0., 0.]]],


        [[[0., 0.]],

         [[0., 0.]]]])


In [48]:
# 重复张量 -- 
# 1. torch.Tensor.repeat(*sizes)    
# 沿着指定的维度重复张量。 不同于 expand()方法，本函数复制的是张量中的数据。 
# 参数: size(torch.Size or int) -沿着每一维度重复的次数  
k_5 = torch.Tensor([1,2,3])
k_6 = k_5.repeat(3,1) 
print('k_6:',k_6)

# 2. torch.Tensor.unfold(dim,size,step) --> Tensor   
# 返回一个新的张量，其中元素 复制于原有张量在 dim维度上面的数据，重复复制size次，复制时的步进值为 step。 
# 参数: 
#    * dim(int)  - 目标维度 
#    * size(int) - 复制重复的次数(展开维度)  
#    * step(int) - 步长

k_7 = torch.arange(1,8)
print('k_7: ',k_7.size(),k_7)  
k_8 = k_7.unfold(0,3,2) 
print('k_8:',k_8.size(),k_8)


k_6: tensor([[1., 2., 3.],
        [1., 2., 3.],
        [1., 2., 3.]])
k_7:  torch.Size([7]) tensor([1, 2, 3, 4, 5, 6, 7])
k_8: torch.Size([3, 3]) tensor([[1, 2, 3],
        [3, 4, 5],
        [5, 6, 7]])


In [56]:
# 缩小张量  
# 1. torch.Tensor.narrow(dim,start,length)
# 返回一个经过缩小后的张量。 操作的维度是由 dim指定。 缩小范围是从 start 开始到 start+length。 
# 执行本方法的张量与 返回的张量共享相同的底层结构  
# 参数: 
#  * dim(int) - 要进行缩小的维度  
#  * start(int) - 开始维度索引  
#  * length(int) - 缩小持续的长度  

l_1 = torch.Tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
l_2 = l_1.narrow(0, 0, 3)  
print('l_2: ',l_2.size(),l_2)  

l_3 = l_1.narrow(1,0,1) 
print('l_3: ',l_3.size(),l_3)

l_2:  torch.Size([3, 3]) tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
l_3:  torch.Size([3, 1]) tensor([[1.],
        [4.],
        [7.]])


In [61]:
# 张量变形  
# 1. torch.Tensor.view(*args) --> Tensor  
# 返回一个具有 相同数据 但是不同形状的张量  
# 返回的张量必须与 原张量有相同的数据 和 相同的元素个数，但是可以有不同的尺寸    
# 一个 tensor 必须是连续的 contiguous() 才能被查看。
# 参数： args(torch.Size or int)  - 理想的指定尺寸  

l_4 = torch.randn(4,4)  
print('l_4',l_4.size(),l_4)   

l_5 = l_4.view([16]) 
print('l_5: ',l_5.size(),l_5)  

l_6 = l_4.view([2,2,4]) 
print('l_6: ',l_6.size(),l_6)

l_4 torch.Size([4, 4]) tensor([[-0.3817,  2.4836, -0.4313, -0.5117],
        [-0.5709,  0.9594,  2.1554, -1.2182],
        [ 0.3045, -0.3556,  0.6329, -0.3100],
        [ 1.1020,  0.8372, -0.9051,  1.9131]])
l_5:  torch.Size([16]) tensor([-0.3817,  2.4836, -0.4313, -0.5117, -0.5709,  0.9594,  2.1554, -1.2182,
         0.3045, -0.3556,  0.6329, -0.3100,  1.1020,  0.8372, -0.9051,  1.9131])
l_6:  torch.Size([2, 2, 4]) tensor([[[-0.3817,  2.4836, -0.4313, -0.5117],
         [-0.5709,  0.9594,  2.1554, -1.2182]],

        [[ 0.3045, -0.3556,  0.6329, -0.3100],
         [ 1.1020,  0.8372, -0.9051,  1.9131]]])


In [63]:
# 重设张量尺寸 
# 1. torch.resize_()    
# 将张量的尺寸调整为指定的大小。 如果元素个数比当前的内存大小大，就将底层存储 大小，调整为 与新元素数目一致的大小。  
# 如果元素个数比当前内存小，则底层存储不会被改变。 原来张量中被保存下来的元素将保持不变，但是新内存不会被初始化。   
# 参数： sizes(torch.Size or int)  -需要调整的大小  
l_7 = torch.Tensor([[1,2],[3,4],[5,6]])  
l_8 = l_7.resize_(2,2)
print('l_8: ',l_8.size(),l_8)

l_8:  torch.Size([2, 2]) tensor([[1., 2.],
        [3., 4.]])


In [69]:
# 置换张量维度  
# 1. torch.Tensor.permute(*dims)  
# 将执行本方法的张量的维度置换。   
# 直接在方法中填入各个维度的索引，张量就会交换指定维度的尺寸，不限于两两交换。
# 参数: dim(int) - 指定换位顺序  
m_1 = torch.randn(2,3,5)  
print('m_1',m_1.size(),m_1)

m_2 = m_1.permute(2,0,1)  
print('m_2: ',m_2.size(),m_2)  


# torch.transpose()  
# torch.transpose(input,dim0,dim1) --> Tensor 
# 返回输入矩阵 input 转置。  交换维度 din0 - dim1. 
# 输入张量与 输出张量共享内存。  

n_1 = torch.randn(2,4,3) 
print('n_1: ',n_1.size(),n_1)  
n_2 = torch.transpose(n_1,1,2)
print('n_2: ',n_2.size(),n_2)

m_1 torch.Size([2, 3, 5]) tensor([[[-0.6380,  1.2446, -0.9995, -1.0774, -1.0818],
         [ 2.2983, -2.1731, -0.6929, -0.2860, -0.7544],
         [ 0.6070, -0.4391, -0.9510, -1.3038, -0.3321]],

        [[ 1.4086,  0.1324, -0.3574, -0.5572,  1.5325],
         [-0.5728, -0.7109, -2.5166, -0.2381,  0.2539],
         [-0.8991,  0.0039, -0.7443, -0.5701, -0.4112]]])
m_2:  torch.Size([5, 2, 3]) tensor([[[-0.6380,  2.2983,  0.6070],
         [ 1.4086, -0.5728, -0.8991]],

        [[ 1.2446, -2.1731, -0.4391],
         [ 0.1324, -0.7109,  0.0039]],

        [[-0.9995, -0.6929, -0.9510],
         [-0.3574, -2.5166, -0.7443]],

        [[-1.0774, -0.2860, -1.3038],
         [-0.5572, -0.2381, -0.5701]],

        [[-1.0818, -0.7544, -0.3321],
         [ 1.5325,  0.2539, -0.4112]]])
n_1:  torch.Size([2, 4, 3]) tensor([[[ 0.5896,  0.6844,  1.1751],
         [-0.2296, -0.8836, -1.8135],
         [-0.2536, -0.1605, -0.8355],
         [-1.1912,  1.4416,  0.4441]],

        [[ 1.4102, -1.2788, -1.607

In [66]:
# 查看张量单个元素的字节数   
# torch.Tensor.element_size() --> int 
# 查看某类型张量单个元素的字节数  
torch.FloatTensor().element_size()

4

In [ ]:
# 矩阵转置 
# torch.t(input) 
# 输入一个矩阵(2维张量),并转置 0-1 维度，可以看作 函数 transpose(input,0,1)的简写函数  